import { UserRole } from "@clearpath/types";
import type { Permission } from "@clearpath/types";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  // ---- PLATFORM ----
  [UserRole.SUPER_ADMIN]: [
    "REFERRAL:CREATE", "REFERRAL:READ", "REFERRAL:UPDATE", "REFERRAL:DELETE", "REFERRAL:LIST", "REFERRAL:EXPORT",
    "CLIENT:CREATE", "CLIENT:READ", "CLIENT:UPDATE", "CLIENT:DELETE", "CLIENT:LIST", "CLIENT:EXPORT",
    "DIAGNOSTIC_CASE:CREATE", "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:UPDATE", "DIAGNOSTIC_CASE:DELETE", "DIAGNOSTIC_CASE:LIST", "DIAGNOSTIC_CASE:ASSIGN",
    "PROVIDER:CREATE", "PROVIDER:READ", "PROVIDER:UPDATE", "PROVIDER:DELETE", "PROVIDER:LIST",
    "PROVIDER_AVAILABILITY:CREATE", "PROVIDER_AVAILABILITY:READ", "PROVIDER_AVAILABILITY:UPDATE", "PROVIDER_AVAILABILITY:LIST",
    "INTERVIEW:CREATE", "INTERVIEW:READ", "INTERVIEW:UPDATE", "INTERVIEW:DELETE", "INTERVIEW:LIST",
    "REPORT:CREATE", "REPORT:READ", "REPORT:UPDATE", "REPORT:DELETE", "REPORT:LIST", "REPORT:APPROVE",
    "BILLING:CREATE", "BILLING:READ", "BILLING:UPDATE", "BILLING:LIST", "BILLING:EXPORT",
    "PAYOUT:CREATE", "PAYOUT:READ", "PAYOUT:UPDATE", "PAYOUT:LIST", "PAYOUT:APPROVE",
    "ORGANIZATION:CREATE", "ORGANIZATION:READ", "ORGANIZATION:UPDATE", "ORGANIZATION:DELETE", "ORGANIZATION:LIST",
    "USER:CREATE", "USER:READ", "USER:UPDATE", "USER:DELETE", "USER:LIST",
    "AUDIT_LOG:READ", "AUDIT_LOG:LIST", "AUDIT_LOG:EXPORT",
    "DASHBOARD_ANALYTICS:READ",
    "CARE_FLAG:CREATE", "CARE_FLAG:READ", "CARE_FLAG:UPDATE", "CARE_FLAG:LIST",
    "OUTREACH:CREATE", "OUTREACH:READ", "OUTREACH:LIST",
    "SETTINGS:READ", "SETTINGS:UPDATE",
  ],

  [UserRole.FINANCE_ADMIN]: [
    "BILLING:READ", "BILLING:UPDATE", "BILLING:LIST", "BILLING:EXPORT",
    "PAYOUT:READ", "PAYOUT:UPDATE", "PAYOUT:LIST", "PAYOUT:APPROVE",
    "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:LIST",
    "ORGANIZATION:READ", "ORGANIZATION:LIST",
    "DASHBOARD_ANALYTICS:READ",
    "AUDIT_LOG:READ", "AUDIT_LOG:LIST",
  ],

  // ---- CLEARPATH INTERNAL ----
  [UserRole.ADMIN]: [
    "REFERRAL:CREATE", "REFERRAL:READ", "REFERRAL:UPDATE", "REFERRAL:LIST", "REFERRAL:EXPORT",
    "CLIENT:CREATE", "CLIENT:READ", "CLIENT:UPDATE", "CLIENT:LIST",
    "DIAGNOSTIC_CASE:CREATE", "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:UPDATE", "DIAGNOSTIC_CASE:LIST", "DIAGNOSTIC_CASE:ASSIGN",
    "PROVIDER:CREATE", "PROVIDER:READ", "PROVIDER:UPDATE", "PROVIDER:LIST",
    "PROVIDER_AVAILABILITY:READ", "PROVIDER_AVAILABILITY:LIST",
    "INTERVIEW:CREATE", "INTERVIEW:READ", "INTERVIEW:UPDATE", "INTERVIEW:LIST",
    "REPORT:READ", "REPORT:LIST", "REPORT:APPROVE",
    "BILLING:READ", "BILLING:LIST",
    "PAYOUT:READ", "PAYOUT:LIST",
    "ORGANIZATION:CREATE", "ORGANIZATION:READ", "ORGANIZATION:UPDATE", "ORGANIZATION:LIST",
    "USER:CREATE", "USER:READ", "USER:UPDATE", "USER:LIST",
    "DASHBOARD_ANALYTICS:READ",
    "CARE_FLAG:CREATE", "CARE_FLAG:READ", "CARE_FLAG:UPDATE", "CARE_FLAG:LIST",
    "OUTREACH:CREATE", "OUTREACH:READ", "OUTREACH:LIST",
    "AUDIT_LOG:READ", "AUDIT_LOG:LIST",
    "SETTINGS:READ", "SETTINGS:UPDATE",
  ],

  [UserRole.INTAKE_COORDINATOR]: [
    "REFERRAL:CREATE", "REFERRAL:READ", "REFERRAL:UPDATE", "REFERRAL:LIST",
    "CLIENT:CREATE", "CLIENT:READ", "CLIENT:UPDATE", "CLIENT:LIST",
    "DIAGNOSTIC_CASE:CREATE", "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:UPDATE", "DIAGNOSTIC_CASE:LIST",
    "PROVIDER:READ", "PROVIDER:LIST",
    "INTERVIEW:READ", "INTERVIEW:LIST",
    "CARE_FLAG:CREATE", "CARE_FLAG:READ", "CARE_FLAG:UPDATE", "CARE_FLAG:LIST",
    "OUTREACH:CREATE", "OUTREACH:READ", "OUTREACH:LIST",
    "DASHBOARD_ANALYTICS:READ",
  ],

  [UserRole.SCHEDULER]: [
    "REFERRAL:READ", "REFERRAL:LIST",
    "CLIENT:READ", "CLIENT:LIST",
    "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:UPDATE", "DIAGNOSTIC_CASE:LIST",
    "PROVIDER:READ", "PROVIDER:LIST",
    "PROVIDER_AVAILABILITY:READ", "PROVIDER_AVAILABILITY:LIST",
    "INTERVIEW:CREATE", "INTERVIEW:READ", "INTERVIEW:UPDATE", "INTERVIEW:LIST",
    "CARE_FLAG:CREATE", "CARE_FLAG:READ", "CARE_FLAG:LIST",
    "DASHBOARD_ANALYTICS:READ",
  ],

  [UserRole.ACCOUNT_MANAGER]: [
    "REFERRAL:READ", "REFERRAL:LIST",
    "CLIENT:READ", "CLIENT:LIST",
    "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:LIST",
    "ORGANIZATION:READ", "ORGANIZATION:UPDATE", "ORGANIZATION:LIST",
    "CARE_FLAG:READ", "CARE_FLAG:LIST",
    "DASHBOARD_ANALYTICS:READ",
  ],

  [UserRole.COMMUNITY_DEVELOPMENT_MANAGER]: [
    "ORGANIZATION:READ", "ORGANIZATION:LIST",
    "REFERRAL:READ", "REFERRAL:LIST",
    "DASHBOARD_ANALYTICS:READ",
  ],

  // ---- SUPPLY SIDE ----
  // Providers see ONLY their own assigned records (enforced at data layer)
  [UserRole.PSYCHOLOGIST]: [
    "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:LIST",
    "CLIENT:READ",
    "INTERVIEW:READ", "INTERVIEW:LIST",
    "PROVIDER_AVAILABILITY:CREATE", "PROVIDER_AVAILABILITY:READ", "PROVIDER_AVAILABILITY:UPDATE", "PROVIDER_AVAILABILITY:LIST",
    "REPORT:CREATE", "REPORT:READ", "REPORT:UPDATE", "REPORT:LIST", "REPORT:APPROVE",
    "PAYOUT:READ", "PAYOUT:LIST",
    "CARE_FLAG:CREATE", "CARE_FLAG:READ",
    "DASHBOARD_ANALYTICS:READ",
  ],

  [UserRole.PSYCHOMETRIST]: [
    "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:LIST",
    "CLIENT:READ",
    "INTERVIEW:READ", "INTERVIEW:LIST",
    "PROVIDER_AVAILABILITY:CREATE", "PROVIDER_AVAILABILITY:READ", "PROVIDER_AVAILABILITY:UPDATE", "PROVIDER_AVAILABILITY:LIST",
    "REPORT:READ", "REPORT:LIST",
    "PAYOUT:READ", "PAYOUT:LIST",
    "CARE_FLAG:CREATE", "CARE_FLAG:READ",
    "DASHBOARD_ANALYTICS:READ",
  ],

  // ---- DEMAND SIDE ----
  // External orgs see ONLY their own organization's records (enforced at data layer)
  [UserRole.ABA_PROVIDER_ADMIN]: [
    "REFERRAL:CREATE", "REFERRAL:READ", "REFERRAL:LIST",
    "CLIENT:READ", "CLIENT:LIST",
    "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:LIST",
    "REPORT:READ",
    "ORGANIZATION:READ",
    "USER:READ", "USER:LIST",
    "DASHBOARD_ANALYTICS:READ",
  ],

  [UserRole.ABA_PROVIDER_STAFF]: [
    "REFERRAL:CREATE", "REFERRAL:READ", "REFERRAL:LIST",
    "CLIENT:READ", "CLIENT:LIST",
    "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:LIST",
    "REPORT:READ",
    "DASHBOARD_ANALYTICS:READ",
  ],

  [UserRole.PEDIATRICIAN_ADMIN]: [
    "REFERRAL:CREATE", "REFERRAL:READ", "REFERRAL:LIST",
    "CLIENT:READ", "CLIENT:LIST",
    "DIAGNOSTIC_CASE:READ", "DIAGNOSTIC_CASE:LIST",
    "REPORT:READ",
    "ORGANIZATION:READ",
    "DASHBOARD_ANALYTICS:READ",
  ],

  // ---- FAMILY ----
  // Parents see ONLY their own child's records (enforced at data layer)
  [UserRole.PARENT_GUARDIAN]: [
    "CLIENT:READ",
    "DIAGNOSTIC_CASE:READ",
    "INTERVIEW:READ",
    "REPORT:READ",
    "DASHBOARD_ANALYTICS:READ",
  ],
};
