// Organization types
export enum OrganizationType {
  DIAGNOSTICS_OPERATOR = "DIAGNOSTICS_OPERATOR",
  ABA_PROVIDER = "ABA_PROVIDER",
  PEDIATRICIAN = "PEDIATRICIAN",
  SCHOOL = "SCHOOL",
  BILLING_PROVIDER = "BILLING_PROVIDER",
}

// User roles (strict RBAC)
export enum UserRole {
  // Platform-level
  SUPER_ADMIN = "SUPER_ADMIN",
  FINANCE_ADMIN = "FINANCE_ADMIN",
  // ClearPath Internal
  ADMIN = "ADMIN",
  INTAKE_COORDINATOR = "INTAKE_COORDINATOR",
  SCHEDULER = "SCHEDULER",
  ACCOUNT_MANAGER = "ACCOUNT_MANAGER",
  COMMUNITY_DEVELOPMENT_MANAGER = "COMMUNITY_DEVELOPMENT_MANAGER",
  // Supply side
  PSYCHOLOGIST = "PSYCHOLOGIST",
  PSYCHOMETRIST = "PSYCHOMETRIST",
  // Demand side
  ABA_PROVIDER_ADMIN = "ABA_PROVIDER_ADMIN",
  ABA_PROVIDER_STAFF = "ABA_PROVIDER_STAFF",
  PEDIATRICIAN_ADMIN = "PEDIATRICIAN_ADMIN",
  // Family
  PARENT_GUARDIAN = "PARENT_GUARDIAN",
}

// Referral status lifecycle (use exactly this order)
export enum ReferralStatus {
  RECEIVED = "RECEIVED",
  INTAKE_IN_PROGRESS = "INTAKE_IN_PROGRESS",
  PARENT_CONTACTED = "PARENT_CONTACTED",
  READY_TO_SCHEDULE = "READY_TO_SCHEDULE",
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
  REPORT_IN_REVIEW = "REPORT_IN_REVIEW",
  REPORT_APPROVED = "REPORT_APPROVED",
  BILLING_SUBMITTED = "BILLING_SUBMITTED",
  DIAGNOSIS_COMPLETE = "DIAGNOSIS_COMPLETE",
  REPORT_DELIVERED = "REPORT_DELIVERED",
  CLOSED = "CLOSED",
}

export enum ReferralChannel {
  FAX = "FAX",
  PHONE = "PHONE",
  PORTAL = "PORTAL",
  EMAIL = "EMAIL",
  WALK_IN = "WALK_IN",
}

export enum ProviderType {
  PSYCHOLOGIST = "PSYCHOLOGIST",
  PSYCHOMETRIST = "PSYCHOMETRIST",
}

export enum CasePriority {
  STANDARD = "STANDARD",
  URGENT = "URGENT",
  EXPEDITED = "EXPEDITED",
}

export enum InterviewType {
  PARENT_INTERVIEW = "PARENT_INTERVIEW",
  CHILD_OBSERVATION = "CHILD_OBSERVATION",
  SCHOOL_OBSERVATION = "SCHOOL_OBSERVATION",
  TESTING_SESSION = "TESTING_SESSION",
  FEEDBACK_SESSION = "FEEDBACK_SESSION",
}

export enum ReportStatus {
  DRAFT = "DRAFT",
  IN_REVIEW = "IN_REVIEW",
  REVISION_REQUESTED = "REVISION_REQUESTED",
  APPROVED = "APPROVED",
  DELIVERED = "DELIVERED",
}

export enum BillingStatus {
  PENDING = "PENDING",
  SUBMITTED = "SUBMITTED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  PAID = "PAID",
  WRITTEN_OFF = "WRITTEN_OFF",
}

export enum PayoutStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  PAID = "PAID",
  VOIDED = "VOIDED",
}

export enum AuditAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  READ_PHI = "READ_PHI",
  EXPORT = "EXPORT",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  PERMISSION_CHANGE = "PERMISSION_CHANGE",
}

export enum FlagSeverity {
  INFO = "INFO",
  WARNING = "WARNING",
  URGENT = "URGENT",
  CRITICAL = "CRITICAL",
}

export enum DayOfWeek {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}
