export enum Resource {
  REFERRAL = "REFERRAL",
  CLIENT = "CLIENT",
  DIAGNOSTIC_CASE = "DIAGNOSTIC_CASE",
  PROVIDER = "PROVIDER",
  PROVIDER_AVAILABILITY = "PROVIDER_AVAILABILITY",
  INTERVIEW = "INTERVIEW",
  REPORT = "REPORT",
  BILLING = "BILLING",
  PAYOUT = "PAYOUT",
  ORGANIZATION = "ORGANIZATION",
  USER = "USER",
  AUDIT_LOG = "AUDIT_LOG",
  DASHBOARD_ANALYTICS = "DASHBOARD_ANALYTICS",
  CARE_FLAG = "CARE_FLAG",
  OUTREACH = "OUTREACH",
  SETTINGS = "SETTINGS",
}

export enum Action {
  CREATE = "CREATE",
  READ = "READ",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  LIST = "LIST",
  EXPORT = "EXPORT",
  APPROVE = "APPROVE",
  ASSIGN = "ASSIGN",
}

export type Permission = `${Resource}:${Action}`;
